// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema/schema.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MethodOptions struct {
	// Types that are valid to be assigned to Type:
	//	*MethodOptions_Query
	//	*MethodOptions_Mutation
	Type                 isMethodOptions_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_98b0d2c3e7e0142d, []int{0}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

type isMethodOptions_Type interface {
	isMethodOptions_Type()
}

type MethodOptions_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type MethodOptions_Mutation struct {
	Mutation string `protobuf:"bytes,2,opt,name=mutation,proto3,oneof"`
}

func (*MethodOptions_Query) isMethodOptions_Type() {}

func (*MethodOptions_Mutation) isMethodOptions_Type() {}

func (m *MethodOptions) GetType() isMethodOptions_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MethodOptions) GetQuery() string {
	if x, ok := m.GetType().(*MethodOptions_Query); ok {
		return x.Query
	}
	return ""
}

func (m *MethodOptions) GetMutation() string {
	if x, ok := m.GetType().(*MethodOptions_Mutation); ok {
		return x.Mutation
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MethodOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MethodOptions_Query)(nil),
		(*MethodOptions_Mutation)(nil),
	}
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         91111,
	Name:          "graphql.schema",
	Tag:           "bytes,91111,opt,name=schema",
	Filename:      "schema/schema.proto",
}

var E_Skip = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         91112,
	Name:          "graphql.skip",
	Tag:           "varint,91112,opt,name=skip",
	Filename:      "schema/schema.proto",
}

var E_Name = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         91114,
	Name:          "graphql.name",
	Tag:           "bytes,91114,opt,name=name",
	Filename:      "schema/schema.proto",
}

var E_Type = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         91117,
	Name:          "graphql.type",
	Tag:           "bytes,91117,opt,name=type",
	Filename:      "schema/schema.proto",
}

var E_FileSkip = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         91113,
	Name:          "graphql.file_skip",
	Tag:           "varint,91113,opt,name=file_skip",
	Filename:      "schema/schema.proto",
}

var E_InputSkip = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         91115,
	Name:          "graphql.input_skip",
	Tag:           "varint,91115,opt,name=input_skip",
	Filename:      "schema/schema.proto",
}

var E_PayloadSkip = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         91116,
	Name:          "graphql.payload_skip",
	Tag:           "varint,91116,opt,name=payload_skip",
	Filename:      "schema/schema.proto",
}

var E_Id = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         91120,
	Name:          "graphql.id",
	Tag:           "varint,91120,opt,name=id",
	Filename:      "schema/schema.proto",
}

func init() {
	proto.RegisterType((*MethodOptions)(nil), "graphql.MethodOptions")
	proto.RegisterExtension(E_Schema)
	proto.RegisterExtension(E_Skip)
	proto.RegisterExtension(E_Name)
	proto.RegisterExtension(E_Type)
	proto.RegisterExtension(E_FileSkip)
	proto.RegisterExtension(E_InputSkip)
	proto.RegisterExtension(E_PayloadSkip)
	proto.RegisterExtension(E_Id)
}

func init() { proto.RegisterFile("schema/schema.proto", fileDescriptor_98b0d2c3e7e0142d) }

var fileDescriptor_98b0d2c3e7e0142d = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0xd2, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0x07, 0x70, 0x37, 0xb6, 0xb9, 0x3e, 0xd3, 0x4b, 0x85, 0x31, 0x74, 0xd3, 0xe1, 0x69, 0xa7,
	0x14, 0x14, 0x2f, 0x13, 0x3c, 0xec, 0x20, 0x5e, 0x86, 0x52, 0x6f, 0x5e, 0x24, 0x5b, 0xb3, 0x2e,
	0x9a, 0x36, 0x59, 0x93, 0x1e, 0xfa, 0x09, 0xfd, 0x28, 0xbe, 0x83, 0x1f, 0x41, 0xf2, 0xb2, 0xc2,
	0x70, 0x50, 0x4f, 0xa5, 0xc9, 0xf3, 0xfb, 0xe7, 0x9f, 0x52, 0x38, 0x90, 0xf3, 0x25, 0x49, 0x70,
	0x60, 0x1f, 0x48, 0x64, 0x5c, 0x71, 0x7f, 0x37, 0xce, 0xb0, 0x58, 0xae, 0xd8, 0xe1, 0x30, 0xe6,
	0x3c, 0x66, 0x24, 0x30, 0xcb, 0xb3, 0x7c, 0x11, 0x44, 0x44, 0xce, 0x33, 0x2a, 0x14, 0xcf, 0xec,
	0xe8, 0xe9, 0x14, 0xf6, 0xa7, 0x44, 0x2d, 0x79, 0x74, 0x2b, 0x14, 0xe5, 0xa9, 0xf4, 0xbb, 0xd0,
	0x5c, 0xe5, 0x24, 0x2b, 0x7a, 0xb5, 0x61, 0x6d, 0xe4, 0xdd, 0xec, 0x84, 0xf6, 0xd5, 0xef, 0x43,
	0x3b, 0xc9, 0x15, 0xd6, 0x43, 0xbd, 0xba, 0xdb, 0x2a, 0x57, 0x26, 0x2d, 0x68, 0xa8, 0x42, 0x90,
	0xf1, 0x1d, 0xb4, 0x6c, 0x13, 0xff, 0x18, 0xd9, 0xb3, 0xd1, 0xfa, 0x6c, 0xb4, 0x71, 0x4e, 0xef,
	0xf5, 0xa5, 0x39, 0xac, 0x8d, 0x3a, 0x67, 0x5d, 0xe4, 0xca, 0x6e, 0xee, 0x87, 0x2e, 0x67, 0x7c,
	0x01, 0x0d, 0xf9, 0x4c, 0x85, 0x7f, 0xb2, 0x25, 0x4f, 0x4a, 0x1c, 0x93, 0x75, 0xe0, 0x9b, 0x09,
	0x6c, 0x87, 0x66, 0x5c, 0xb3, 0x14, 0x27, 0xa4, 0x9a, 0x7d, 0x18, 0xe6, 0x85, 0x66, 0x5c, 0x33,
	0x7d, 0x8f, 0x6a, 0xf6, 0xbd, 0x66, 0xe6, 0xda, 0x97, 0xe0, 0x2d, 0x28, 0x23, 0x8f, 0xa6, 0x69,
	0xff, 0x8f, 0xbd, 0xa6, 0xac, 0x84, 0xef, 0xae, 0x66, 0x5b, 0x83, 0x7b, 0x5d, 0xf5, 0x0a, 0x80,
	0xa6, 0x22, 0x57, 0x56, 0x0f, 0xb6, 0x68, 0xc2, 0xca, 0xcf, 0xf6, 0xe9, 0xb8, 0x67, 0x88, 0xf1,
	0x13, 0xd8, 0x13, 0xb8, 0x60, 0x1c, 0x47, 0xff, 0x4a, 0xf8, 0x72, 0x09, 0x1d, 0x87, 0x4c, 0x46,
	0x00, 0x75, 0x1a, 0x55, 0xc9, 0x1f, 0x27, 0xeb, 0x34, 0x9a, 0x0c, 0x1e, 0x8e, 0x62, 0x8e, 0xb0,
	0x10, 0x9c, 0xa6, 0xaa, 0x40, 0x73, 0x9e, 0x04, 0x4f, 0x18, 0x33, 0xf7, 0x1f, 0xce, 0x5a, 0x26,
	0xe1, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xe3, 0xe2, 0x62, 0x9f, 0x02, 0x00, 0x00,
}
